baseURL          = "https://cogsandsquigs.gq"
copyright        = "(c) Ian Pratt 2022"
enableGitInfo    = true
languageCode     = "en-us"
sectionPagesMenu = "main"
theme            = "cogs"
title            = "Cogs and Squigs"

## THEME PARAMS ##
[[menus.main]]
    name   = "home"
    url    = "/"
    weight = 1

[[menus.main]]
    name   = "about"
    url    = "/about"
    weight = 2

[[menus.main]]
    name   = "blog"
    url    = "/blog"
    weight = 3

[[menus.main]]
    name   = "github"
    url    = "https://github.com/cogsandsquigs"
    weight = 4

[taxonomies]
    category = "categories"
    series   = "series"
    tag      = "tags"

# parameters
[params]
    dateFormat = "Monday, Jan 2, 2006"

    [params.github]
        repo = "cogsandsquigs"
        user = "cogsandsquigs"

## MISC. PARAMS ##
[markup]
    defaultMarkdownHandler = "goldmark"

    [markup.goldmark.extensions]
        katex = true

[minify]
    minifyOutput = true

    [minify.tdewolff]

        [minify.tdewolff.css]
            keepCSS2  = true
            precision = 0

        [minify.tdewolff.html]
            keepComments            = false
            keepConditionalComments = true
            keepDefaultAttrVals     = true
            keepDocumentTags        = true
            keepEndTags             = true
            keepQuotes              = false
            keepWhitespace          = false

        [minify.tdewolff.js]
            keepVarNames      = false
            noNullishOperator = false
            precision         = 0

        [minify.tdewolff.json]
            keepNumbers = false
            precision   = 0

        [minify.tdewolff.svg]
            keepComments = false
            precision    = 0

        [minify.tdewolff.xml]
            keepComments   = false
            keepWhitespace = false
