author      = "Ian Pratt"                          # The default author name used in the meta tags
description = "My little slice of the blogosphere" # The site description
title       = "Cogs And Squigs"                    # The site title 

base_url      = "https://cogsandsquigs.dev" # The URL the site will be built for
feed_filename = "atom.xml"                  # The name of the RSS feed file

build_search_index = true    # Whether to build a search index to be used later on by a JavaScript library
compile_sass       = true    # Whether to automatically compile all Sass files in the sass directory
minify_html        = true    # Whether to minify the HTML output
output_dir         = "build" # The output directory that will contain the site build

[markdown]
	highlight_code  = true      # Whether to do syntax highlighting
	highlight_theme = "dracula" # The syntax highlighting theme to use

[extra]
	# Put all your custom variables here
