baseURL       = "http://cogsandsquigs.gq/"
copyright     = "© {author} 2019-{year}"
enableGitInfo = true
languageCode  = "en-us"
minify        = true
theme         = "cogs"
title         = "Cogs And Squigs"

[author]
  name = "Ian Pratt"

[taxonomies]
  series = 'series'
  tag    = 'tags'

[languages]
  [languages.en]
    keywords               = ""
    languageName           = "English"
    menuMore               = "Show me more!"
    missingBackButtonLabel = "Why don't you go back home?"
    missingContentMessage  = "Whatever you're looking for - it doesn't exist. Sorry."
    newerPosts             = "Newer posts"
    olderPosts             = "Older posts"
    readMore               = "Read more"
    readOtherPosts         = "Read other posts"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name       = "About"
        url        = "/about"

      [[languages.en.menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"

      [[languages.en.menu.main]]
        identifier = "github"
        name       = "Github"
        url        = "https://github.com/cogsandsquigs"

[outputFormats]
  [outputFormats.RSS]
    baseName  = "rss"
    mediatype = "application/rss"

[params]
  # The directory to your favicons from the `static` folder. Requires '/' at the end
  # if it's a folder
  # faviconDir = "" # No favicon dir

  # If we use KaTeX or not
  useKatex = true

  # Any and all options for rendering KaTeX, in the spec defined on the KaTeX docs 
  # website.
  [params.katex]

    delimiters = [
      { left = "$$", right = "$$", display = true },
      { left = "$", right = "$", display = false },
      { left = "\\(", right = "\\)", display = false },
      { left = "\\[", right = "\\]", display = true },
    ]

    throwOnError = false

    trust = true

    # {
    # 	// customised options
    # 	// • auto-render specific keys, e.g.:
    # 	delimiters: [
    # 		{ left = "$$", right= "$$", display= true },
    # 		{ left = "$", right= "$", display= false },
    # 		{ left = "\\(", right= "\\)", display= false },
    # 		{ left = "\\[", right= "\\]", display= true }
    # 	],

    # 	// • rendering keys, e.g.:
    # 	throwOnError: false,

    # 	// This should
    # 	trust: true
    # }
