---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- name: repo_link
  type: text
  config:
    required: false
  label: repo_link
- type: list
  name: tags
  label: tags
- type: boolean
  name: draft
  label: draft
